In [1]:
import numpy as np
import pandas as pd

In [ ]:
#1 Examen

In [ ]:
#2 Crear un vector de ceros de tamaño 10

In [2]:
vector_ceros = np.zeros(10)
vector_ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#3 Crear un vector de ceros de tamaño 10 y el de la posicion 5 sea igual a 1

In [3]:
vector_ceros = np.zeros(10)
vector_ceros[4] = 1
vector_ceros

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
#4 Cambiar el orden de un vector de 50 elementos, el de la posición 1 es el de la 50 etc.

In [4]:
vector_cincuenta = np.arange(50)
vector_cincuenta[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [ ]:
#5 Crear una matriz con valores del cero al 8

In [5]:
matriz_3 = np.arange(9)
matriz_3.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#6 Encontrar los índices que no sean cero en un arreglo

In [8]:
arreglo  = np.array([1,2,0,0,4,0])
mayores_cero = arreglo > 0
arreglo[mayores_cero]

array([1, 2, 4])

In [ ]:
#7 Crear una matriz de identidad de 3x3

In [10]:
matriz_ident = np.eye(3)
matriz_ident

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#8 Crear una matriz de 3x3x3 con valores randomicos

In [11]:
matriz_randomica = np.random.randint(0,20,(3,3,3))
matriz_randomica

array([[[ 8, 12,  1],
        [11,  6,  7],
        [ 4, 10,  9]],

       [[ 4,  5,  2],
        [19, 14,  5],
        [10,  3,  1]],

       [[12, 19,  5],
        [ 5, 17, 11],
        [ 7, 10,  6]]])

In [ ]:
#9 Crear una matriz 10x10 y encontrar el mayor y el menor

In [14]:
matriz_mayor_menor = np.random.randint(0,79,(10,10))
print("La matriz es\n")
print(matriz_mayor_menor)
print("El numero mayor es\n")
print(np.max(matriz_mayor_menor))
print("El numero menor es\n")
print(np.min(matriz_mayor_menor))

La matriz es

[[52 48 52 44 60 63 21 70 52  2]
 [68 21 64 30 47  2 70 41 10 21]
 [43 11 54 48 15 34 44 53 45 36]
 [31 59 41 40 22 47  4 23 57 56]
 [74 72 56 62 14 64 43 13 77 60]
 [56 74  2 30 41 77 35 57 15 10]
 [75 73  1 47 47 70 61 77 26 76]
 [11 36 19 21 50 10 77 42 33 17]
 [26 18 67 24 58 21 19 40 62 66]
 [12 75 18 34 17 17 21 60 25  6]]
El numero mayor es

77
El numero menor es

1


In [ ]:
#10 Sacar los colores RGB unicos en una imagen (cuales rgb existen ej: 0, 0, 0 - 255,255,255 -> 2 colores)