In [1]:
# pip install numpy
# conda install numpy

import numpy as np 

In [3]:
print(type([1,2,3]))
print(type((1,2,3)))


<class 'list'>
<class 'tuple'>


In [13]:
np.zeros(5) #Funciona para hacer calculos matemáticos 

#Arreglos multidimensionales 
np.zeros([5,5])
np.zeros((2,5)) # 1 lista o tupla para una matriz de nxm dimensiones

np.zeros([5,3,4]) # n dimensiones
np.zeros([1000,200])
np.zeros([2,3,4,5])

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [15]:
np.ones(7)
np.ones((1,2,3,4))

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [17]:
np.eye(10) #Matriz de nxn

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [18]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [19]:
np.arange(4,20) # [4,20[ intervalo en donde la izquierda es abierto y la derecha es cerrado

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [21]:
np.arange(-12,1) # [-12,1[ 

array([-12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [22]:
np.arange(0,20,3) # con esta declaración el elemento va a ir saltando de 3 en 3

array([ 0,  3,  6,  9, 12, 15, 18])

In [24]:
np.arange(0,2.1,0.2) #También se puede con decimales 

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [26]:
resultado = np.arange(1,21)*3
print(resultado)

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60]


In [27]:
np.arange(10) #Solo es una dimension por diez elementos

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
np.zeros(20).reshape(2,5,2).reshape(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [32]:
resultado = np.arange(1,21)+10
print(resultado)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


In [34]:
# Para saber el numero de elementos dentro de un arreglo
len(np.ones(12))

12

In [35]:
len(np.ones(12).reshape(4,3))

4

In [36]:
np.ones(12).reshape(4,3) # Cambiamos las dimensiones 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
np.ones(12).reshape(4,3).shape # Con el shape vemos el numero de dimensiones 

(4, 3)

In [39]:
np.arange(12).reshape(4,3)[1,2]

5

In [40]:
np.array([1,7,12,16]).reshape(2,2)

array([[ 1,  7],
       [12, 16]])

In [47]:
a = np.array([10,10,10])
b = np.array([5,5,8])

In [48]:
#suma
a + b

array([15, 15, 18])

In [49]:
#Resta 
a - b

array([5, 5, 2])

In [50]:
# suma con un escalar 
a + 25

array([35, 35, 35])

In [51]:
# Resta con un escalar 
b - 2

array([3, 3, 6])

In [52]:
# Multiplicacion
a * b

array([50, 50, 80])

In [53]:
b * 3

array([15, 15, 24])

In [54]:
# Division
a/b

array([2.  , 2.  , 1.25])

In [55]:
# Modulo
a % b


array([0, 0, 2], dtype=int32)

In [56]:
# Modulo 
a % 3


array([1, 1, 1], dtype=int32)

In [57]:
muestra = np.arange(20)

In [58]:
muestra

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [71]:
respuesta_glucosa = muestra > 5

In [72]:
respuesta_glucosa

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [73]:
muestra[respuesta_glucosa] # Aquí ya nos da filtrando

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [74]:
respuesta_nueva_glucosa = muestra < 14

In [75]:
respuesta_nueva_glucosa

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
       False, False])

In [76]:
muestra[respuesta_glucosa & respuesta_nueva_glucosa]

array([ 6,  7,  8,  9, 10, 11, 12, 13])

In [79]:
numeros = muestra[respuesta_glucosa & respuesta_nueva_glucosa]

In [82]:
muestra[respuesta_glucosa & respuesta_nueva_glucosa] % 2

array([0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [83]:
numeros

array([ 6,  7,  8,  9, 10, 11, 12, 13])

In [86]:
if numeros % 2 == 0:
    print(numeros)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
#Clase 30/06/2020

In [3]:
#Producto punto en matrices
A = np.arange(4).reshape((2,2))
A

array([[0, 1],
       [2, 3]])

In [12]:
B = np.arange(4,8).reshape((2,2))
B

array([[4, 5],
       [6, 7]])

In [13]:
#Producto punto 
np.dot(A,B) #El método DOT me devuelve el producto punto de las dos matrices 

array([[ 6,  7],
       [26, 31]])

In [5]:
arreglo_doce = np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
#Se puede usar algunas funciones cuando se crea el arreglo 
arreglo_doce.sum()  #Suma todos los elementos del arreglo

66

In [8]:
arreglo_doce.min() #Se puede sacar el minimo valor 

0

In [9]:
arreglo_doce.max() #Nos permite sacar el máximo valor del arreglo

11

In [11]:
arreglo_doce[6:].sum() #Así se puede seleccionar una parte del arreglo o de donde a donde quiero que sume

51

In [14]:
arreglo_doce.reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [18]:
arreglo_doce.reshape(3,2,2).sum()

66

In [19]:
#Se puede sumar cada eje de la matriz
arreglo_doce.reshape(3,2,2).sum(axis=0)

array([[12, 15],
       [18, 21]])

In [20]:
arreglo_doce.reshape(3,2,2).sum(axis=1)

array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [21]:
arreglo_doce.reshape(3,2,2).sum(axis=2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])