In [1]:
import numpy as np

In [2]:
arreglo_de_grados = np.array([0,30,45,60,90,110,135])
arreglo_de_grados

array([  0,  30,  45,  60,  90, 110, 135])

In [3]:
arreglo_radianes = arreglo_de_grados * np.pi / 180 #La librería numpy se lleva super bien con funciones y también tiene pi 
arreglo_radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633,
       1.91986218, 2.35619449])

In [4]:
np.sin(arreglo_radianes) #Se puede usar todas las funciones trigonométricas

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ,
       0.93969262, 0.70710678])

In [5]:
np.tan(arreglo_radianes)

array([ 0.00000000e+00,  5.77350269e-01,  1.00000000e+00,  1.73205081e+00,
        1.63312394e+16, -2.74747742e+00, -1.00000000e+00])

In [9]:
#Tambíén se puede crear un arreglo randomico de enteros
# Lo que le estamos diciendo con 11, devuelveme un numero entero hasta el 11 [0,11[
numero_random = np.random.randint(11)
numero_random

7

In [15]:
numero_random_negativo = np.random.randint(-9,2) #desde el -9 hasta el 2 [-9,1[
numero_random_negativo

-4

In [18]:
#arreglo_random = np.random.randint(10,20) #Con esta opcion solo nos devuelve un solo numero randomico pero nosotros queremos más
arreglo_random = np.random.randint(10,20,8) #Aquí nos devuelve un arreglo
arreglo_random

array([13, 11, 13, 17, 11, 17, 18, 14])

In [19]:
np.random.rand(9) #Nos sirve para decimales

array([0.14486537, 0.5429291 , 0.21835071, 0.97262246, 0.87130928,
       0.39824268, 0.69866588, 0.56362572, 0.17097888])

In [20]:
np.random.rand(27).reshape(3,3,3) #Nos sirve para decimales

array([[[0.52610529, 0.24388713, 0.60675984],
        [0.73257237, 0.00835917, 0.58790477],
        [0.48735369, 0.76969305, 0.87470793]],

       [[0.45993584, 0.0516635 , 0.73434295],
        [0.47030772, 0.18874099, 0.2718279 ],
        [0.89026954, 0.64704741, 0.27073337]],

       [[0.17668835, 0.66943717, 0.69450837],
        [0.22696214, 0.52626082, 0.76720512],
        [0.8213468 , 0.47667021, 0.94272285]]])

In [23]:
#Funciones estadísticas 
np.average(arreglo_random) #Para sacar el promedio

14.25

In [24]:
np.mean(arreglo_random)

14.25

In [25]:
np.median(arreglo_random)

13.5

In [26]:
np.std(arreglo_random)

2.5860201081971503

In [27]:
np.var(arreglo_random)

6.6875

In [28]:
arreglo_random.mean()

14.25